### ISSUE TITLE
Type alias returns `any` bug

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#340]
Investigate why our type alias returns `any` instead of the specific type.
<img width="642" alt="Screenshot 2021-04-06 at 4 28 36 PM" src="https://user-images.githubusercontent.com/19917616/113683182-7c82cc00-96f6-11eb-9cbc-2987b1dfe7f7.png">

**Comment by prestonlimlianjie** [comment]
Update:
We accidentally defined `Checker` as both a type and interface in the `checker.d.ts` file. Only the interface export is properly defined, while the type export is `any`. 

We want to figure out how to use the type export properly since the type export is created using a `Pick<>` of the Checker model Class (for a more detailed explanation, read https://github.com/opengovsg/checkfirst/pull/285 section on **We want to modify the codebase to look to the model class as the main source of types)**.

```export interface Checker {
  id: string
  title: string
  description?: string
  users?: User[]

  fields: Field[]
  constants: Constant[]
  operations: Operation[]
  displays: Display[]
}

export type Checker = Pick<
  CheckerModel,
  'id',
  'title',
  'description',
  'fields',
  'constants',
  'operations',
  'displays'
>```

**Comment by lamkeewei** [comment]
I think the issue is that we have to do something like `class Checker extends Model<CheckerType>` when defining the model. Since the [type definition](https://github.com/RobinBuschmann/sequelize-typescript/blob/a222d79626780437277d3b6af12b11b3925243cf/src/model/model/model.ts#L27) for `Model` in `sequelize-typescript` is `Model<TModelAttributes extends {} = any, TCreationAttributes extends {} = TModelAttributes >`, if we don't provide a generic type, I guess it defaults to `any`.
