### ISSUE TITLE
Numeric field does not recognise 0 as valid value

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/checkfirst#676]
**Describe the bug**
When the value of a numeric field is 0, a not found error is thrown when evaluating an expression.

**To Reproduce**
1. Create a new numeric field
2. Use numeric field in a calculated result
3. Go to preview and submit (leaving value as 0)
4. Error should be thrown

**Comment by orbitalsqwib** [comment]
Note: after testing, I noticed that 0 does in fact work as a valid value but only after you key it in again (trigger an onChange event in the numeric field). <s>I suspect this has something to do with the context not initialising the field values properly.</s> Update: turns out to be a null coercion issue within the submission function. Fix coming shortly.
