### ISSUE TITLE
Help button menu changes

### ISSUE THREAD

**Issue by rlyss** [opengovsg/checkfirst#880]
**Is your feature request related to a problem? Please describe.**
The context-aware help button menu should provide clearer navigation and be more maintainable when it comes to adding new features and pages into the guide. It can also act in place of an announcement modal to introduce users to features when they are creating a checker.

**Describe the solution you'd like**

- Condense block guides into a single option for each of the tabs
- Add new option to main overview help menu page for tutorials
- When a new checker is created, the help menu should automatically be opened to the main overview "Help & Resources" page. This should only happen on first creation of the checker.

https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=3167%3A45499

**Comment by NatMaeTan** [comment]
Based on 27th Jul 2021 discussion:

1. Condense all the block guides into a single option, then redirect user to respective block pages in the guide. 
– Will be harder to maintain separate guides for each logic blocks in the future, this is easier to maintain. Menu items should be more high-level stuff
<img width="400" alt="Help_LogicTab" src="https://user-images.githubusercontent.com/63220614/127285608-67306fc7-d4b2-4a93-8fb9-b9299d517224.png">
<img width="400" alt="Help_ConstantsTab" src="https://user-images.githubusercontent.com/63220614/127285614-002d011a-773e-4f9c-95f3-81137e6c11b4.png">
<img width="400" alt="Help_QuestionsTab" src="https://user-images.githubusercontent.com/63220614/127285622-57ff4e0f-1441-4b14-afed-0f8269436a0a.png">


2. Added a new option to the 'main' page for tutorials

3. Help button should open "Help & Resources" on first creation. Users have to close the menu themselves by clicking on the button.
– Since we have no announcement modal to announce the new help button changes, we need to showcase this change. But this is only on first creation!
<img width="400" alt="NewChecker" src="https://user-images.githubusercontent.com/63220614/127285580-1b148cc3-ac57-404c-92c1-464d008b4cfb.png">


[Behaviour prototype](https://www.figma.com/proto/qtoA63mFtCW3jGYhr8ev7y/Master?page-id=2759%3A0&node-id=3168%3A48063&viewport=2563%2C-4916%2C0.2137337625026703&scaling=min-zoom&starting-point-node-id=3168%3A46462)
[Condensed help menu items for diff tabs](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=3167%3A45499)
